[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Sseve", email = "719283952@qq.com"},
]
dependencies = [
    "grpcio>=1.51.1",
    "grpcio-tools>=1.51.1",
    "fabric>=3.0.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
